# development version of app.yaml
# only meant for use with gae dev_appserver.py
# use the app.yaml in repo root for deploying with appcfg.py

application: getlanternhr
version: "2013-06-28"
runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.sh
- ^(.*/)?.*\.y[a]?ml
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.s[ca]ss
- ^(.*/)?.*\.jar
- ^(.*/)?.*/node_modules/.*
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$

handlers:

- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /
  static_dir: '.'
  secure: always
